config/routes.rb
DigitalEnvy::Application.routes.draw do
  get "products/index"

  get "products/show"

  root to: "sessions#new"
  resources :products
  match "/auth/storenvy/callback", to: "sessions#create"
  match "/auth/failure", to: "sessions#failure"
  match "/logout", to: "sessions#destroy", :as => "logout"
  
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :login
  
  has_many :products
  
  def self.from_storenvy(auth)
    Rails.logger.info(auth.inspect)
    user = find_by_storenvy_id(auth["uid"]) || create_with_storenvy(auth)
    user.update_column(:access_token, auth['credentials']['token']) unless user.nil?
    user
  end

  def self.create_with_storenvy(auth)
    create! do |user|
      user.storenvy_id = auth["uid"]
      user.login       = auth["info"]["login"]
      user.email       = auth["info"]["email"]
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  
  def oauth_client
    OAuth2::Client.new(Storenvy_app_id, Storenvy_secret, :site => 'https://api.storenvy.com')
  end
  
  def storenvy_reusable_access_token(user)
    OAuth2::AccessToken.from_hash(
      oauth_client,
       {"access_token" => user.access_token}
    )
  end
  
  def storenvy_store_info(user)
    storenvy_reusable_access_token(user).get("/v1/store").parsed["data"].symbolize_keys
  end
  
  def storenvy_products(user, params = {})
    response = storenvy_reusable_access_token(user).get("/v1/products?#{params.to_query}").parsed
    Rails.logger.info(response)
    response["data"]["products"].map &:symbolize_keys
  end
  
  def login_required
    return if current_user
    flash[:error] = "Please log in to do that."
    redirect_to root_url and return false
  end
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :login_required
  
  def index
    @products = storenvy_products(current_user)
    @store    = storenvy_store_info(current_user)
  end

  def show
  end
  
  def new
    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.from_storenvy(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

  def failure
    redirect_to root_url, alert: "Authentication failed, please try again."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalEnvy</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/index.html.erb
<h1>My Products</h1>
<h3><%= link_to @store[:name], @store["url"] %></h3>
<%= image_tag(@store[:avatar]) %>
<%= button_to "New Product", new_product_path, method: :get %>
<table border="0" cellspacing="5" cellpadding="5">
  <tr><th>Product Name</th><th>Price</th><th>File</th></tr>
  <%- @products.each do |product| -%>
  <tr><td><%= product[:name] %></td><td>$<%= product[:price] %></td><td><%= link_to "Create Download", new_product_path(:product_id => product[:id]) %></td></tr>
  <%- end -%>
</table>

app/views/products/new.html.erb
hi.

app/views/products/show.html.erb
<h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p>